---
name: 'lint yaml'
description: 'lint a yaml'
author: 'BieggerM'
inputs:
  have-fun:
    description: 'have fun'
    required: true
  do-stuff:
    description: 'do stuff'
    required: true
outputs:
  have-fun:
    description: 'have fun'
  do-stuff:
    description: 'do stuff'
runs:
  using: 'docker' 
  image: 'Dockerfile'
