---
name: 'lint yaml'
description: 'lint a yaml'
author: 'BieggerM'
inputs:
  dir:
    description: 'Directory where the yaml files are located'
    required: true
  schema:
    description: 'Schema against which is being validated'
    required: true
  filename:
    description: 'Filename for a specific yaml file to lint'
    required: false
runs:
  using: 'docker' 
  image: 'Dockerfile'
